create table if not exists public.payment_config (
  id boolean primary key default true check (id),
  deposit_percentage numeric(5,2) not null default 50 check (deposit_percentage > 0 and deposit_percentage <= 100),
  pix_expiration_minutes integer not null default 15 check (pix_expiration_minutes between 5 and 1440),
  allow_cash boolean not null default true,
  max_installments integer not null default 1 check (max_installments between 1 and 12),
  updated_at timestamptz not null default now()
);

insert into public.payment_config (id, deposit_percentage, pix_expiration_minutes, allow_cash, max_installments)
values (true, 50, 15, true, 1)
on conflict (id) do update set
  deposit_percentage = excluded.deposit_percentage,
  pix_expiration_minutes = excluded.pix_expiration_minutes,
  allow_cash = excluded.allow_cash,
  updated_at = now();

alter table public.appointments
  add column if not exists expires_at timestamptz,
  add column if not exists confirmed_at timestamptz,
  add column if not exists amount_due numeric(10,2),
  add column if not exists amount_paid numeric(10,2) not null default 0,
  add column if not exists payment_percentage numeric(5,2);

update public.appointments
set amount_due = coalesce(amount_due, price),
    payment_percentage = coalesce(payment_percentage, 100),
    confirmed_at = case when status = 'Confirmado' then coalesce(confirmed_at, created_at) else confirmed_at end
where amount_due is null or payment_percentage is null or (status = 'Confirmado' and confirmed_at is null);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null references public.appointments(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete restrict,
  provider text not null default 'mercado_pago' check (provider in ('mercado_pago')),
  provider_payment_id text,
  idempotency_key uuid not null default gen_random_uuid(),
  amount numeric(10,2) not null check (amount > 0),
  currency text not null default 'BRL' check (currency = 'BRL'),
  method text not null check (method in ('pix', 'card')),
  status text not null default 'pending' check (status in ('pending', 'in_process', 'approved', 'rejected', 'cancelled', 'expired', 'refunded', 'charged_back', 'error')),
  status_detail text,
  qr_code text,
  qr_code_base64 text,
  ticket_url text,
  expires_at timestamptz,
  paid_at timestamptz,
  refunded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (appointment_id),
  unique (provider_payment_id),
  unique (idempotency_key)
);

create table if not exists public.appointment_items (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null references public.appointments(id) on delete cascade,
  service_id uuid references public.services(id) on delete set null,
  service_name text not null,
  unit_price numeric(10,2) not null check (unit_price >= 0),
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  unique (appointment_id, service_id)
);

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  provider text not null default 'mercado_pago',
  provider_event_id text not null,
  provider_payment_id text,
  event_type text,
  payload_hash text,
  result text,
  processed_at timestamptz not null default now(),
  unique (provider, provider_event_id)
);

create index if not exists payments_user_created_idx on public.payments (user_id, created_at desc);
create index if not exists payments_status_idx on public.payments (status, expires_at);
create index if not exists appointment_items_appointment_idx on public.appointment_items (appointment_id);
create unique index if not exists appointments_active_slot_unique
on public.appointments (appointment_date, appointment_time)
where status in ('Confirmado', 'Aguardando pagamento');

alter table public.payment_config enable row level security;
alter table public.payments enable row level security;
alter table public.appointment_items enable row level security;
alter table public.payment_events enable row level security;

drop policy if exists payment_config_authenticated_read on public.payment_config;
create policy payment_config_authenticated_read
on public.payment_config for select to authenticated using (true);

drop policy if exists payment_config_admin_all on public.payment_config;
create policy payment_config_admin_all
on public.payment_config for all to authenticated
using (app_private.is_admin()) with check (app_private.is_admin());

drop policy if exists payments_read_own on public.payments;
create policy payments_read_own
on public.payments for select to authenticated
using (exists (
  select 1 from public.users u
  where u.id = payments.user_id and u.auth_user_id = auth.uid()
));

drop policy if exists payments_admin_read on public.payments;
create policy payments_admin_read
on public.payments for select to authenticated using (app_private.is_admin());

drop policy if exists appointment_items_read_own on public.appointment_items;
create policy appointment_items_read_own
on public.appointment_items for select to authenticated
using (exists (
  select 1
  from public.appointments a
  join public.users u on u.id = a.user_id
  where a.id = appointment_items.appointment_id and u.auth_user_id = auth.uid()
));

drop policy if exists appointment_items_admin_read on public.appointment_items;
create policy appointment_items_admin_read
on public.appointment_items for select to authenticated using (app_private.is_admin());

grant select on public.payment_config, public.payments, public.appointment_items to authenticated;
revoke all on public.payment_events from anon, authenticated;

drop function if exists public.get_booked_slots(date);

create function public.get_booked_slots(target_date date)
returns table (appointment_time time)
language sql
security definer
set search_path = public
as $$
  update public.appointments
  set status = 'Expirado', payment_status = 'Expirado', updated_at = now()
  where status = 'Aguardando pagamento'
    and expires_at is not null
    and expires_at <= now();

  select a.appointment_time
  from public.appointments a
  where a.appointment_date = target_date
    and (
      a.status = 'Confirmado'
      or (a.status = 'Aguardando pagamento' and a.expires_at > now())
    )
  order by a.appointment_time;
$$;

grant execute on function public.get_booked_slots(date) to anon, authenticated;
